### ISSUE TITLE
CheckSeverity is not exposed in extension

### ISSUE THREAD

**Issue by robert3005** [tbroyer/gradle-errorprone-plugin#10]
If you try to follow the readme and try to do

```
tasks.named("compileJava").configure {
    options.errorprone.check("NullAway", CheckSeverity.ERROR)
}
```

```
> Could not get unknown property 'CheckSeverity' for -XepDisableWarningsInGeneratedCode -Xep:EqualsHashCode:ERROR -Xep:EqualsIncompatibleType:ERROR -Xep:StreamResourceLeak:ERROR of type net.ltgt.gradle.errorprone.ErrorProneOptions.
```

You need to either add an import to your gradle file or otherwise this plugin has to expose CheckSeverity as a property on extension

**Comment by tbroyer** [comment]
See #8

I'll update the readme to add the import, but I'm not going to add a hack to this plugin just so users (of the Gradle DSL, not the Kotlin DSL) don't have to add an import; unless maybe a Gradle core team member recommends otherwise.
