### ISSUE TITLE
disableWarningsInGeneratedCode doesn't work when building with JDK 11

### ISSUE THREAD

**Issue by msridhar** [tbroyer/gradle-errorprone-plugin#17]
In NullAway there is the Error Prone config `disableWarningsInGeneratedCode = true` [here](https://github.com/uber/NullAway/blob/736dd4e27f248ac955793e16137f9fad41750112/build.gradle#L48).  This works fine on JDK 8, but when building on JDK 11, I am still getting warnings in the generated code; see [this Travis build](https://travis-ci.org/uber/NullAway/jobs/462507005).  So it seems the option is not working when building on JDK 11?

**Comment by tbroyer** [comment]
There's no `@Generated` annotation in the AutoValue-generated sources. This is because you're using `-source 1.8` (through `sourceCompatibility`) and not `--release 8`; see https://github.com/google/auto/issues/686

That can be fixed with something like:
```gradle
if (JavaVersion.current().java9Compatible) {
  tasks.withType(JavaCompile) {
    options.compilerArgs += [ "--release", "8" ]
  }
}
```
