### ISSUE TITLE
error: plug-in not found: ErrorProne with android.enableSeparateAnnotationProcessing=true

### ISSUE THREAD

**Issue by bubenheimer** [tbroyer/gradle-errorprone-plugin#19]
When using `android.enableSeparateAnnotationProcessing=true`, the build fails with `error: plug-in not found: ErrorProne`

This is with plugin version 0.6.1, Gradle 5.1, AGP 3.3.0-rc03 or 3.4.0-alpha10
And:

    dependencies {
        errorprone 'com.google.errorprone:error_prone_core:2.3.2'
        errorproneJavac 'com.google.errorprone:javac:9+181-r4173-1'
    }

Besides its regular purpose of enabling incremental compilation I have found the gradle property essential for working around https://github.com/google/error-prone/issues/771

**Comment by tbroyer** [comment]
It seems to be a limitation of the Android plugin for Gradle: apparently they are special-casing Lombok, but should also special-case compiler plugins such as Error Prone (or configure the `annotationProcessorPath` irrespective of whether they configure `-proc:none`). Please report the issue there.
