### ISSUE TITLE
API 'variant.getjavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()' It will be removed at the end of 2019

### ISSUE THREAD

**Issue by evant** [tbroyer/gradle-errorprone-plugin#22]
Getting this warning with the latest android gradle plugin

**Comment by tbroyer** [comment]
Just a FYI: I'm aware of that already, and started working on a fix last weekend. I still have to test it against earlier versions of the Android SDK though to make sure I don't introduce a regression.
