### ISSUE TITLE
Add to readme where to find versions of javac

### ISSUE THREAD

**Issue by stephanenicolas** [tbroyer/gradle-errorprone-plugin#23]
Hi @tbroyer , thx very much for updating the errorprone plugin to agp 3.3.0 and gradle 5.

While migrating from version 0.0.11 to 0.7, I was wondering where to get an appropriate javac version for error prone. I ended up looking into the code and realized you were using a dependency of error prone itself. Maybe you should add this to the doc: 

 You can find an appropriate version of javac for errorprone on [maven central](https://search.maven.org/search?q=g:com.google.errorprone%20AND%20a:javac&core=gav).

**Comment by tbroyer** [comment]
See #18. We can reopen the discussion though. Maybe add some note to the "migrate from v0.0.x" section to run `./gradlew dependencyInsight --configuration errorprone --dependency javac` before upgrading?
