### ISSUE TITLE
Custom Javac plugin does not launch together with ErrorProne

### ISSUE THREAD

**Issue by dmdashenkov** [tbroyer/gradle-errorprone-plugin#31]
I'm trying to run a custom plugin together with the ErrorProne plugin.

When the ErrorProne Gradle plugin is not applied, my Javac plugin is launched. However, when it is applied, my plugin is skipped (it is still discovered by the `ServiceLoader`, but the `init` method is never called).

I was able to work around this issue, by satisfying this [condition](https://github.com/tbroyer/gradle-errorprone-plugin/blob/master/src/main/kotlin/net/ltgt/gradle/errorprone/ErrorPronePlugin.kt#L87):
```gradle
compileJava {
    options.compilerArgs += '-Xplugin:MyPlugin'
    options.fork = true
    if (options.forkOptions.javaHome == null) {
        options.forkOptions.javaHome = System.getenv('JAVA_HOME') as File
    }
}
```
but the compiler now fails at some random spot, which, I believe, is why there is a custom ErrorProne Javac in the first place.

How do I enable custom Javac plugins with the ErrorProne Java compiler?

I'm using Java 8, ErrorProne `2.3.3`, ErrorProne Javac `9+181-r4173-1`, and the Gradle plugin `0.8`.

**Comment by dmdashenkov** [comment]
Not sure if this is the right repository for this issue, maybe it is something related to the ErrorProne Javac itself or the core repository.

**Comment by tbroyer** [comment]
See https://github.com/tbroyer/gradle-errorprone-plugin/tree/v0.8#jdk-8-support

> The plugin will try to detect those cases and won't configure the bootstrap classpath in this case, but to play safe it will actually ignore any task that forks and defines either a javaHome or an executable (this also means that it won't configure the bootstrap classpath if you're e.g. running Gradle with a more recent JDK and forking the compilation tasks to use JDK 8).

Your snippet above disables the `-Xbootclasspath/p:` (see https://errorprone.info/docs/installation#java-8) so it's likely that Error Prone will crash as a result.

This looks like some incompatibility between your plugin and ErrorProne Javac.

You'll probably want to try invoking Javac on the command line on a small project to validate this assumption (fwiw, you can run Gradle with debug logs and extract the full set of Javac arguments from there). You may want to try with Java 9+ too (which won't change the bootstrap classpath).
