### ISSUE TITLE
Could not set unknown property 'enabled' for  of type net.ltgt.gradle.errorprone.ErrorProneOptions.

### ISSUE THREAD

**Issue by davidliu** [tbroyer/gradle-errorprone-plugin#32]
Just doing:

    tasks.withType(JavaCompile).configureEach {
        if (name.toLowerCase().contains("debug")) {
            options.errorprone.enabled = false
        }
    }

Seems to work with version 0.7, but when I upgrade to 0.8, this error appears:

`Could not set unknown property 'enabled' for  of type net.ltgt.gradle.errorprone.ErrorProneOptions.`

**Comment by tbroyer** [comment]
In [0.8](https://github.com/tbroyer/gradle-errorprone-plugin/releases/tag/v0.8), all properties were changed to _lazy properties_, and Gradle uses some bytecode generation tricks to allow Groovy DSL users to use the `=` operator to assign new values, but I must say I haven't checked the impact of changing a `boolean` to `Property<Boolean>` in the Groovy DSL (I exclusively use the Kotlin DSL).

Can you try with `isEnabled` instead? (that's how the property is named in Kotlin)
```gradle
options.errorprone.isEnabled = false
```

**Comment by davidliu** [comment]
options.errorprone.isEnabled = false

doesn't work either.

I think it may have something to do with the "is" prefix. The `isCompilingTestOnlyCode` property has similar issues. See the following screenshots:

![Screen Shot 2019-05-31 at 10 56 48 AM](https://user-images.githubusercontent.com/242400/58725307-aa2cba80-8393-11e9-9358-a5c8299fac53.png)

![Screen Shot 2019-05-31 at 10 51 24 AM](https://user-images.githubusercontent.com/242400/58724786-579ece80-8392-11e9-8572-4d7aec58bac0.png)

Note that while the getters are there, the setters are missing. Additionally, these values are only accessible by calling the method explicitly. That is, `options.errorprone.isEnabled()` will return the value fine, while `options.errorprone.isEnabled` errors.

**Comment by tbroyer** [comment]
Ok, that's what I suspected: because they're no longer `boolean isXxx()` but `Property<Boolean> isXxx()` they're no longer seen as properties (no longer following the Java Beans naming convention), and Gradle no longer generates the setters.

I'll fix that in a 0.9, and in the mean time you can use `options.errorprone.isEnabled().set(false)`

**Comment by tbroyer** [comment]
I just released v0.8.1 with a fix.
