### ISSUE TITLE
Error prone plugin uses fork

### ISSUE THREAD

**Issue by emartynov** [tbroyer/gradle-errorprone-plugin#33]
Is there a reason why error-prone starts in a fork? If I'm not mistaken original javac just runs on a gradle daemon.

I was getting OOM with javac and I didn't find an easy way how to specify more memory for the error-prone java fork.

**Comment by tbroyer** [comment]
See https://github.com/tbroyer/gradle-errorprone-plugin#jdk-8-support

When using JDK 8, an ErrorProne-specific JavaC needs to be prepended to the bootstrap classpath, which requires forking a separate JVM. That being said, the forked process should still be reused by all compile tasks, used as a Gradle worker daemon (by default, Gradle compiles "in process" of its global daemon)

I'd suggest using JDK 11 along with `--release 8` (`options.compilerArgs.addAll(["--release", "8"])`) if you can; or configure memory requirements on the `options.forkOptions` (https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:fork), e.g. `options.forkOptions.memoryMaximumSize`, or through `options.forkOptions.jvmArgs`.

**Comment by emartynov** [comment]
Thank you for the update.

I also was not able the make fork options to work with the next setting:
```
tasks.withType(JavaCompile) {
    options.forkOptions.memoryMaximumSize = "1g"
}
```

Probably I'm missing something.

**Comment by tbroyer** [comment]
I'd suggest:
* running with `--info` or `--debug` logs to see what arguments are passed to the worker process (AFAICT you should see lines beginning with `JVM Arg:` in the logs)
* asking for help in the [Gradle forum](https://discuss.gradle.org/) or [Gradle Community Slack](https://gradle-community.slack.com)

You could also, temporarily, for debugging the situation, disable ErrorProne (or remove the plugin entirely) and try configuring the task's forking manually:
```gradle
tasks.withType(JavaCompile).configureEach {
  options.errorprone.enabled = false
  options.fork = true
  options.forkOptions.memoryMaximumSize = "4m" // should fail the build as it's too low
}
```

I'm afraid I won't be able to help you much more…

**Comment by emartynov** [comment]
Thank you!
