### ISSUE TITLE
ErrorProne Performance Problems

### ISSUE THREAD

**Issue by Blisse** [tbroyer/gradle-errorprone-plugin#34]
Hi! I'm noticing non-insignificant slowdowns when using Error Prone in our Android project, which is making it hard to fully adopt.

```
  errorProneVersion = '2.3.3'
  errorProneJavacVersion = '9+181-r4173-1'
  errorProneGradlePluginVersion = '0.8.1'
...
  core: "com.google.errorprone:error_prone_core:${errorProneVersion}",
  gradle_plugin: "net.ltgt.gradle:gradle-errorprone-plugin:${errorProneGradlePluginVersion}",
  javac: "com.google.errorprone:javac:${errorProneJavacVersion}",
...
  classpath deps.error_prone.gradle_plugin
...
  project.dependencies {
    errorprone deps.error_prone.core
    errorproneJavac deps.error_prone.javac
  }
```

Essentially I'm looking at the single task compilation speed drop from 2s to 8s after turning on Error Prone with the default checks. There's a margin of error but you can clearly see a trend 2s -> 8s, and 0.4s -> 3s after repeated runs.

| Test Case | Single task time after 2nd run (compileDebugKotlin) | .. (compileDebugJavaWithJavac) | Total task time
| -- | -- | -- | -- |
| w/ Error Prone+NullAway | 9873ms |  8343ms  | BUILD SUCCESSFUL in 3m 50s |
| large module w/ Error Prone only | 10252ms  | 8655ms | BUILD SUCCESSFUL in 4m 4s  |
| small module w/ Error Prone only  |  603ms |   2823ms | BUILD SUCCESSFUL in 59s |
| large module w/o Error Prone | 13933ms | 1560ms   | BUILD SUCCESSFUL in 4m 31s  |
| small module w/o Error Prone |  662ms | 350ms | BUILD SUCCESSFUL in 56s |

Would you have any advice on the matter?

**Comment by tbroyer** [comment]
Error Prone does have an overhead, yes: https://github.com/google/error-prone/issues/994

I don't think the Gradle plugin contributes to that overhead though, so closing.
