### ISSUE TITLE
Not working with APT

### ISSUE THREAD

**Issue by mkadan** [tbroyer/gradle-errorprone-plugin#4]
When I enable `'net.ltgt.apt'` plugin the build starts to fail. Maybe this has something to do with APT overriding default compile targets and ErrorProne has to be additionally configured? I've seen this in `README.md`, but could you provide a way to do that for already existing `'compileJava'` and `'compilteTestJava'` targets? Unfortunately, I have not that much Gradle experience to do that myself.

```
> Task :compileJava FAILED
error: plug-in not found: ErrorProne
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
```

I also attach a sample project to reproduce the issue:
[demo.zip](https://github.com/tbroyer/gradle-errorprone-javacplugin-plugin/files/2275278/demo.zip)

**Comment by mkadan** [comment]
As a matter of fact, to resolve the issue I managed to use `'annotationProcessor'` instead of `'apt'` while declaring my dependencies, so I could remove `'net.ltgt.apt'` plugin. I'm using Gradle 4.6+, so this works perfectly. I guess I'm just closing the issue, as `'gradle-errorprone-javacplugin-plugin'` is intended for use with Gradle 4.6+ anyway.

**Comment by tbroyer** [comment]
This is because you're using an old version of `net.ltgt.apt` that predates the `annotationProcessor` configurations. Use at least 0.14, otherwise it would overwrite the default Gradle behavior.

`net.ltgt.apt` could still be useful though, see https://github.com/tbroyer/gradle-apt-plugin/issues/80
