### ISSUE TITLE
In Kotlin DSL errorprone plugin with apply=false does not work

### ISSUE THREAD

**Issue by dapengzhang0** [tbroyer/gradle-errorprone-plugin#40]
If you create an empty project using groovy DSL and add errorprone plugin with apply=false as follows:

`build.gradle`
```gradle
plugins {
    id 'net.ltgt.errorprone' version '1.1.1' apply false
}

subprojects {
    apply 'net.ltgt.errorprone'

    repositories {
        mavenCentral()
    }

    dependencies {
        errorprone 'com.google.errorprone:error_prone_core:latest.release'
    }
}
```
then your build is successful.

However, if you create an empty project using Kotlin DSL and add errorprone plugin with apply=false as follows:

`build.gradle.kts`
```kts
plugins {
    id("net.ltgt.errorprone") version "1.1.1" apply false 
}

subprojects {
    apply(plugin = "net.ltgt.errorprone")

    repositories {
        mavenCentral()
    }

    dependencies {
        errorprone("com.google.errorprone:error_prone_core:latest.release")
    }
}
```

then your build fails:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'build.gradle.kts' line: 13

* What went wrong:
Script compilation error:

  Line 13:         errorprone("com.google.errorprone:error_prone_core:latest.release")
                   ^ Unresolved reference: errorprone

1 error
```

**Comment by tbroyer** [comment]
Gradle won't generate the `DependencyHandler.errorprone` extension function if you don't apply the plugin.

You can either apply the plugin (in absence of the `java-base` or any Android plugin, it will create the configurations, triggering Gradle to generate the extension function and configure `JavaCompile` tasks without enabling ErrorProne on them), or use the string notation:
```kotlin
dependencies {
  "errorprone"("com.google.errorprone:error_prone_core:…")
}
```
(as noted [in the README](https://github.com/tbroyer/gradle-errorprone-plugin/blob/master/README.md#usage), I highly discourage using `latest.release` or any dynamic version)

**Comment by dapengzhang0** [comment]
>Gradle won't generate the DependencyHandler.errorprone extension function if you don't apply the plugin.

I don't understand it. Isn't line 5 `apply(plugin = "net.ltgt.errorprone")` applying the plugin?

**Comment by tbroyer** [comment]
Type-safe accessors (such as the `DependencyHandler.errorprone` extension function for declaring dependencies in the `errorprone` configuration) are only generated when applying the the plugin through the `plugins{}` DSL.
See https://docs.gradle.org/current/userguide/kotlin_dsl.html#type-safe-accessors

So when I said “You can either apply the plugin” I meant removing the `apply false`, to apply the plugin to the root project that you're currently configuring.

**Comment by dapengzhang0** [comment]
Thanks for the explanation!
