### ISSUE TITLE
Is JDK8 still not recommended?

### ISSUE THREAD

**Issue by nkiesel** [tbroyer/gradle-errorprone-plugin#44]
I just saw the announcement of version 2.4.0 or error-prone and that states that version 2.4.0 is compatible with JDK8.  Does that mean that this plugin with error-prone-2.4.0 will work w/o "com.google.errorprone:javac:9+181-r4173-1"?

**Comment by tbroyer** [comment]
`com.google.errorprone:javac` will always be needed with JDK 8.
https://errorprone.info/docs/installation

The recommendation to use JDK 9+ is mine though, not an official statement from the ErrorProne developers (AFAICT)
