### ISSUE TITLE
Using Error Prone with Gradle build caching

### ISSUE THREAD

**Issue by sergeykad** [tbroyer/gradle-errorprone-plugin#49]
Is it possible to use Error Prone with Gradle build caching somehow? If the caching enabled, all the reported issues disappear on the second build run. 
For example, [Warnings Next Generation](https://plugins.jenkins.io/warnings-ng/) Jenkins plugin marks all issues as solved if build was performed using build cache.

**Comment by tbroyer** [comment]
This is the intended behavior with Gradle, independent of Error Prone (which only adds warnings/errors during standard Java compilation).

For example, if you use a deprecated API (e.g. most `java.util.Date` constructors and methods) and compile that, you'll have a warning in the output (maybe pass `-Xlint` in `options.compilerArgs` too), and Jenkins will display it.
Now if you rebuild and Gradle resolves from the build cache, you won't have the warning.
And this is without even using Error Prone.
