### ISSUE TITLE
New release to support Gradle 6.7 toolchains?

### ISSUE THREAD

**Issue by anuraaga** [tbroyer/gradle-errorprone-plugin#50]
Hello, sorry to bug but Gradle 6.7 is out and is awesome. I believe my build logs this when Gradle is run with Java 8 and build uses Java 11 because the toolchains support hasn't been released yet. Would be wonderful if that could be released!

```
No dependency was configured in configuration errorproneJavac, compilation with Error Prone will likely fail as a result.
Add a dependency to com.google.errorprone:javac with the appropriate version corresponding to the version of Error Prone you're using:

    dependencies {
        errorproneJavac("com.google.errorprone:javac:$errorproneJavacVersion")
    }
```

**Comment by tbroyer** [comment]
Thanks for the reminder, v1.3.0 is now up in the Plugins Portal.
