### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.common.collect.Streams

### ISSUE THREAD

**Issue by wecheng** [tbroyer/gradle-errorprone-plugin#62]
@tbroyer 
I followed this link https://github.com/tbroyer/gradle-errorprone-plugin to import error prone plugin to my project, but saw this error.

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/24379059/120657279-efba7b80-c4b6-11eb-9e4b-6a83f9a64241.png">

My updates:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/24379059/120657688-4d4ec800-c4b7-11eb-9c1b-0209d21c88b7.png">

<img width="683" alt="image" src="https://user-images.githubusercontent.com/24379059/120657796-65264c00-c4b7-11eb-95db-d20a94a3abc8.png">

**Comment by tbroyer** [comment]
Closing in favor of https://github.com/uber/NullAway/issues/484
