### ISSUE TITLE
Gradle remote build cache misses on all compilation tasks

### ISSUE THREAD

**Issue by sergeykad** [tbroyer/gradle-errorprone-plugin#65]
Compilation results from CI cannot be reused locally due to some differences in the plugin inputs. It is not a location difference since moving the project locally does not cause local cache misses. However, the remote cache populated by CI cannot be reused on the local machine.
Gradle scan produces the following output, but unfortunately, there are no details. It just says that values are different. Even the `doFirst` action implementation reported as different.

![image](https://user-images.githubusercontent.com/12783618/126600558-afffa7c5-3fe7-4c36-92d1-d0d2c716e478.png)

I am using the 2.0.2 version of the plugin.

**Comment by iNikem** [comment]
@sergeykad why did you close this issue? Did you find any resolution to it?

**Comment by sergeykad** [comment]
@iNikem yes. As I discovered, one of Gradle's plugin jars had a different checksum on the CI server.
I solved it by simply upgrading the plugin version that caused a fresh version to be downloaded everywhere. Deleting the cached plugin version on the CI server would have worked too.
