### ISSUE TITLE
Include javac.parser in adds-opens

### ISSUE THREAD

**Issue by ben-manes** [tbroyer/gradle-errorprone-plugin#67]
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.errorprone.util.ErrorProneTokens$CommentSavingTokenizer (file:/Users/ben/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_check_api/2.9.0/fe4decdb87a17bd5583147d96b0fdb852985b333/error_prone_check_api-2.9.0.jar) to field com.sun.tools.javac.parser.JavaTokenizer.reader
WARNING: Please consider reporting this to the maintainers of com.google.errorprone.util.ErrorProneTokens$CommentSavingTokenizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I believe you missed adding the parser,
```
'--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED'
```

https://github.com/tbroyer/gradle-errorprone-plugin/blob/4494aa521c3e7b9d37003cda4045cadad6841533/src/main/kotlin/net/ltgt/gradle/errorprone/ErrorPronePlugin.kt#L58-L69

**Comment by tbroyer** [comment]
I'm using the same set of flags as in the ErrorProne documentation: https://errorprone.info/docs/installation

Given that the `reader` fields doesn't exist in JDK 16 then maybe this is actually an expected warning.
Could you file an issue on ErrorProne itself and/or comment on https://github.com/google/error-prone/issues/1872?

**Comment by ben-manes** [comment]
I suppose it is because my project is JDK-11 (caffeine) and the above is correct for JDK16 (work). Since pre-16 it is warning and not and error, you're right it is probably expected and ignorable as transitional. I think it is perhaps more your choice about this plugin's defaults which is available across multiple JDK versions and if you want the warning shown or suppressed. Either is fine imho, and I suppressed it in my build by adding the jvmArgs option.

**Comment by tbroyer** [comment]
Ah, with JDK 11, those flags won't be used at all (this allows running the compiler in-process, whereas with JDK 16+ there will always be a forked compile daemon to pass those flags, even if Gradle itself runs with the same JDK).
I'm thinking about some refactoring so maybe I'll include those flags with JDK 9+ whenever forking, and force forking with JDK16+ ; maybe this will only be with Gradle 7.1+ through `options.fork.jvmArgumentProviders` though.
