### ISSUE TITLE
semver still? 0.6.+ doesn't match 0.6

### ISSUE THREAD

**Issue by xenoterracide** [tbroyer/gradle-errorprone-plugin#7]
previously I could have matched 0.0.+ as a dep for my plugin (which is just shared settings), now however I can't match match 0.6.+ since the release wasn't 0.6.0, but 0.6. is this still using semantic versioning or will the next version be 0.7, 0.8 etc. is there still a safe way to match api versions? (this is a question but alos maybe a bug, if this *is* still semantically versioned, then the version should be 0.6.0)

**Comment by xenoterracide** [comment]
> (0.y.z)

^ you'll note it still has 3 digits.

https://xenoterracide.com/post/falsehoods-programmers-believe-about-versions/

in any sense I don't feel like I have much time to argue, just seeing what your plan is... however I've noted in the past that changes like this do tend to break "API" just when it comes to package managers handling the version. Being this is jvm code, and not a huge project like scala, I doubt anyone is packaging outside of your packaging though.

**Comment by tbroyer** [comment]
Just a last note that just because I used a three-component version (`0.0.x`) didn't mean it was semver.
