### ISSUE TITLE
Running tests using CompilationTestHelper needs jvmArgs...

### ISSUE THREAD

**Issue by asautins** [tbroyer/gradle-errorprone-plugin#74]
I am developing a custom error prone check for error prone 2.18 running on java 17.   Using the `net.ltgt.errorprone` plugin works great for building.  However, when I adda test class that uses CompilationTestHelper as follow:
```java
public class LogMethodCallParameterTest
{
    private CompilationTestHelper compilationHelper;

    @BeforeEach
    public void setup() {
        compilationHelper = CompilationTestHelper.newInstance(CustomErrorProneCheck.class, getClass());
    }

    @Test
    public void simpleTestCase() {
        compilationHelper.addSourceFile("/testcase1.java").doTest();
    }
}
```

I get the following error when executing the test:

```
java.lang.IllegalAccessError: class com.google.errorprone.CompilationTestHelper (in unnamed module @0x614635c2) cannot access class com.sun.tools.javac.api.JavacTool (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x614635c2
```

I am able to resolve the issue by adding the following to the test section of my `build.gradle` file:

```groovy
test {
   useJUnitPlatform()

   jvmArgs = ['--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED',
              '--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED',
              '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED',
              '--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED',
              '--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED',
              '--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED',
              '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED',
              '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED',
              '--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED',
              '--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED']

}
```

These are the same args as in `ErrorPronePlugin.kt` `JVM_ARGS_STRONG_ENCAPSULATION`.

Am I missing something?  Is there a flag I can add to the test section of my `build.gradle` file to add the strong encapsulation arguments when running tests using `CompilationTestHelper`?

**Comment by tbroyer** [comment]
Those are the flags from https://errorprone.info/docs/installation and yes you'd need to explicitly add them to the `Test` task's `jvmArgs`. There's no specific support for this in the plugin such that it would add those flags for you (writing a check is not the most current kind of projects, and technically you could very well write such a check without checking your code with ErrorProne and therefore without this plugin :wink: e.g. writing it in Kotlin, Groovy or Scala).

Regarding the need for the flags, I think it'd be a good reason to open an issue on the ErrorProne project for them to add some documentation about `CompilationTestHelper` and the required flags (which are, logically, just the same as when using ErrorProne as a compiler plugin, but used differently).
