### ISSUE TITLE
error_prone_core 3.1.0 not found

### ISSUE THREAD

**Issue by rbento** [tbroyer/gradle-errorprone-plugin#81]
Configured Gradle as per the [README.md](https://github.com/tbroyer/gradle-errorprone-plugin#usage)

```
errorprone("com.google.errorprone:error_prone_core:$errorproneVersion")
```

Resulting in the following error:

```
> Could not resolve all files for configuration ':app:annotationProcessor'.
   > Could not find com.google.errorprone:error_prone_core:3.1.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_core/3.1.0/error_prone_core-3.1.0.pom
```

The checked the repository and noticed it is not present:
- https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_core/

**Comment by tbroyer** [comment]
Indeed the latest version of ErrorProne is 2.20: https://github.com/google/error-prone/releases
3.1.0 is the latest version of the Gradle plugin for ErrorProne.
