### ISSUE TITLE
The readme does not give enough information

### ISSUE THREAD

**Issue by mattfbacon** [tbroyer/gradle-errorprone-plugin#84]
For someone relatively unfamiliar with gradle, I would appreciate a bit more detailed explanation of where to put the snippets described in the readme.

**Comment by tbroyer** [comment]
All the snippets are "top-level" so, besides the `plugins { … }` block and `import` statement that need to appear at the top, you can copy/paste them right at the end of your build script.

I'd highly suggest learning Gradle a bit more though (their doc is great) to grasp what each snippet is doing so you can configure further.

Enjoy!
